import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAuditLogsTable1781961493423 implements MigrationInterface {
    name = 'CreateAuditLogsTable1781961493423'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ticket_types" DROP CONSTRAINT "FK_ticket_types_event"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_orders_user"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_order"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_event"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_tickets_ticket_type"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('CREATE', 'READ', 'UPDATE', 'DELETE')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_resource_enum" AS ENUM('USER', 'ROLE', 'ABILITY', 'EVENTS', 'TICKET_TYPES', 'ORDERS', 'CHECKIN')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "uuid" character varying(36) NOT NULL DEFAULT gen_random_uuid(), "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "deleted_at" TIMESTAMP, "action" "public"."audit_logs_action_enum" NOT NULL, "resource" "public"."audit_logs_resource_enum" NOT NULL, "description" character varying(255) NOT NULL, "actor_id" integer, "actor_name" character varying(50), "actor_email" character varying(256), "actor_role" character varying(50), "target_id" character varying(100), "http_method" character varying(10) NOT NULL, "path" character varying(255) NOT NULL, "status_code" integer NOT NULL, "success" boolean NOT NULL DEFAULT true, "ip_address" character varying(45), "metadata" jsonb, CONSTRAINT "UQ_809d3a75a6776bfecf54c8aab35" UNIQUE ("uuid"), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id")); COMMENT ON COLUMN "audit_logs"."id" IS 'Código de identificação do registro'; COMMENT ON COLUMN "audit_logs"."uuid" IS 'Código UUID do registro'; COMMENT ON COLUMN "audit_logs"."created_at" IS 'Data de criação do registro'; COMMENT ON COLUMN "audit_logs"."updated_at" IS 'Data de atualização do registro'; COMMENT ON COLUMN "audit_logs"."deleted_at" IS 'Data de deleção do registro'; COMMENT ON COLUMN "audit_logs"."action" IS 'Ação realizada (CREATE, READ, UPDATE ou DELETE)'; COMMENT ON COLUMN "audit_logs"."resource" IS 'Recurso administrativo afetado pela ação'; COMMENT ON COLUMN "audit_logs"."description" IS 'Descrição da ação realizada, extraída da rota'; COMMENT ON COLUMN "audit_logs"."actor_id" IS 'Código do usuário que realizou a ação'; COMMENT ON COLUMN "audit_logs"."actor_name" IS 'Nome do usuário que realizou a ação no momento da ação'; COMMENT ON COLUMN "audit_logs"."actor_email" IS 'Email do usuário que realizou a ação no momento da ação'; COMMENT ON COLUMN "audit_logs"."actor_role" IS 'Referência do perfil do usuário no momento da ação'; COMMENT ON COLUMN "audit_logs"."target_id" IS 'Identificador do registro afetado pela ação (id ou uuid)'; COMMENT ON COLUMN "audit_logs"."http_method" IS 'Método HTTP utilizado na requisição'; COMMENT ON COLUMN "audit_logs"."path" IS 'Caminho da rota acessada'; COMMENT ON COLUMN "audit_logs"."status_code" IS 'Código de status HTTP retornado pela requisição'; COMMENT ON COLUMN "audit_logs"."success" IS 'Informa se a ação foi concluída com sucesso'; COMMENT ON COLUMN "audit_logs"."ip_address" IS 'Endereço IP de origem da requisição'; COMMENT ON COLUMN "audit_logs"."metadata" IS 'Parâmetros, query e corpo da requisição (sanitizados, sem dados sensíveis)'`);
        await queryRunner.query(`COMMENT ON TABLE "audit_logs" IS 'Tabela para armazenar a trilha de auditoria das ações administrativas'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."uuid" IS 'Código UUID do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."created_at" IS 'Data de criação do registro'`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ALTER COLUMN "created_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."updated_at" IS 'Data de atualização do registro'`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ALTER COLUMN "updated_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."deleted_at" IS 'Data de deleção do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."name" IS 'Nome do tipo de ingresso (ex: Pista, VIP, Camarote)'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."description" IS 'Descrição do tipo de ingresso'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."price" IS 'Preço unitário do ingresso'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."quantity" IS 'Quantidade total de ingressos disponíveis deste tipo'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."sold_quantity" IS 'Quantidade de ingressos já vendidos deste tipo'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."active" IS 'Se o tipo de ingresso está ativo para venda'`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."event_id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."uuid" IS 'Código UUID do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."created_at" IS 'Data de criação do registro'`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."updated_at" IS 'Data de atualização do registro'`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "updated_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."deleted_at" IS 'Data de deleção do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."title" IS 'Título do evento'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."slug" IS 'Identificador amigável do evento utilizado nas URLs públicas'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."description" IS 'Descrição completa do evento'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."image" IS 'URL do banner/imagem do evento'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."location" IS 'Local onde o evento será realizado'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."start_date" IS 'Data e hora de início do evento'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."end_date" IS 'Data e hora de término do evento'`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."status" IS 'Status do evento (ativo/inativo)'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."uuid" IS 'Código UUID do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."created_at" IS 'Data de criação do registro'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."updated_at" IS 'Data de atualização do registro'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."deleted_at" IS 'Data de deleção do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."customer_name" IS 'Nome do cliente que realizou a compra'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."customer_email" IS 'Email do cliente que realizou a compra'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."customer_document" IS 'CPF do cliente (opcional)'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."total" IS 'Valor total do pedido'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."status" IS 'Status do pedido'`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."user_id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."uuid" IS 'Código UUID do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."created_at" IS 'Data de criação do registro'`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "created_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."updated_at" IS 'Data de atualização do registro'`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "updated_at" SET DEFAULT ('now'::text)::timestamp(6) with time zone`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."deleted_at" IS 'Data de deleção do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."code" IS 'Código único do ingresso, usado na validação de entrada'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."qr_code" IS 'QR Code do ingresso codificado como data-URL (imagem base64)'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."status" IS 'Status do ingresso'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."used_at" IS 'Data e hora em que o ingresso foi utilizado no check-in'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."order_id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."event_id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."ticket_type_id" IS 'Código de identificação do registro'`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ADD CONSTRAINT "FK_9dfa62b35548ea1e0b7e4675b20" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bd5636236f799b19f132abf8d70" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_bd5387c23fb40ae7e3526ad75ea" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_a95369aeea12da7fde110e95e00" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_a95369aeea12da7fde110e95e00"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bd5387c23fb40ae7e3526ad75ea"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_bd5636236f799b19f132abf8d70"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "ticket_types" DROP CONSTRAINT "FK_9dfa62b35548ea1e0b7e4675b20"`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."ticket_type_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."event_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."order_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."used_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."qr_code" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."code" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."deleted_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."updated_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "tickets" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."uuid" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "tickets"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."user_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."total" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."customer_document" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."customer_email" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."customer_name" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."deleted_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."updated_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."uuid" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."end_date" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."start_date" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."location" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."image" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."description" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."slug" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."title" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."deleted_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."updated_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "events" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."uuid" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."event_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."active" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."sold_quantity" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."quantity" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."price" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."description" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."name" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."deleted_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."updated_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."created_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."uuid" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ticket_types"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "audit_logs" IS NULL`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_resource_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_ticket_type" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_tickets_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_orders_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_types" ADD CONSTRAINT "FK_ticket_types_event" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
